apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-icons-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-icons-api
  template:
    metadata:
      labels:
        app: crypto-icons-api
    spec:
      containers:
        - image: mdfarhaan/crypto-icons-api
          name: crypto-icons-api

---
apiVersion: v1
kind: Service
metadata:
  name: crypto-icons-api-service
spec:
  selector:
    app: crypto-icons-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
